---

- name: directory to hold public keys
  file: state=directory path=/tmp/pubkeys mode=0755

- name: fetch public keys from github
  get_url: dest=/tmp/pubkeys/{{ item }}-pubkeys url=https://github.com/{{ item }}.keys force=yes
  with_items: github_usernames
  when: github_usernames is defined and github_usernames != []

- name: copy original authorized keys file
  command: cp /root/.ssh/authorized_keys /tmp/pubkeys
  # works only in ansible 2.0 copy: src=/root/.ssh/authorized_keys dest=/tmp/pubkeys/authorized_keys remote_src=True force=yes

- name: assemble the authorized keys file
  assemble: dest=/root/.ssh/authorized_keys mode=0600 src=/tmp/pubkeys
  become: true
  when: github_usernames is defined and github_usernames != []
